// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoCronoVianda.Core.Data;

#nullable disable

namespace ProyectoCronoVianda.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.AsignacionVianda", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<int?>("AprobadoPor")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCronogramaItem")
                        .HasColumnType("int");

                    b.Property<int>("IdMenu")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoVianda")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdCronogramaItem");

                    b.HasIndex("IdMenu");

                    b.HasIndex("IdTipoVianda");

                    b.ToTable("AsignacionesVianda");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdLog");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.ConfiguracionServicioTurno", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.HasKey("IdConfiguracion");

                    b.HasIndex("IdServicio");

                    b.HasIndex("IdTurno");

                    b.ToTable("ConfiguracionesServicioTurno");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Cronograma", b =>
                {
                    b.Property<int>("IdCronograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCronograma"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("IdCronograma");

                    b.HasIndex("IdServicio", "Mes", "Anio")
                        .IsUnique();

                    b.ToTable("Cronogramas");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.CronogramaItem", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCronograma")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.HasKey("IdItem");

                    b.HasIndex("IdCronograma");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdTurno");

                    b.ToTable("CronogramaItems");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TipoDietaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasFilter("[CodigoBarras] IS NOT NULL");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("IdServicio");

                    b.HasIndex("TipoDietaId");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Inasistencia", b =>
                {
                    b.Property<int>("IdInasistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInasistencia"));

                    b.Property<string>("ArchivoSoporteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNotificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RevisadoPor")
                        .HasColumnType("int");

                    b.HasKey("IdInasistencia");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Inasistencias");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenu"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoDieta")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMenu");

                    b.HasIndex("IdTipoDieta");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EntregaViandaHabilitada")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdServicio");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.SolicitudCambioTurno", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpleadoSugerido")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionResolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResueltoPor")
                        .HasColumnType("int");

                    b.Property<string>("TurnoDestino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TurnoOrigen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("SolicitudesCambioTurno");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.TipoDieta", b =>
                {
                    b.Property<int>("IdTipoDieta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDieta"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoDieta");

                    b.ToTable("TiposDieta");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.TipoVianda", b =>
                {
                    b.Property<int>("IdTipoVianda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoVianda"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("IdTipoVianda");

                    b.ToTable("TiposVianda");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTurno");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.VentanaCambio", b =>
                {
                    b.Property<int>("IdVentana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVentana"));

                    b.Property<TimeSpan>("HoraLimiteCambio")
                        .HasColumnType("time");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoVianda")
                        .HasColumnType("int");

                    b.Property<int?>("IdTurno")
                        .HasColumnType("int");

                    b.HasKey("IdVentana");

                    b.HasIndex("IdServicio");

                    b.HasIndex("IdTipoVianda");

                    b.HasIndex("IdTurno");

                    b.ToTable("VentanasCambio");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.AsignacionVianda", b =>
                {
                    b.HasOne("ProyectoCronoVianda.Core.Models.CronogramaItem", "CronogramaItem")
                        .WithMany("AsignacionesVianda")
                        .HasForeignKey("IdCronogramaItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoCronoVianda.Core.Models.Menu", "Menu")
                        .WithMany("AsignacionesVianda")
                        .HasForeignKey("IdMenu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoCronoVianda.Core.Models.TipoVianda", "TipoVianda")
                        .WithMany("AsignacionesVianda")
                        .HasForeignKey("IdTipoVianda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CronogramaItem");

                    b.Navigation("Menu");

                    b.Navigation("TipoVianda");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.AuditLog", b =>
                {
                    b.HasOne("ProyectoCronoVianda.Core.Models.Usuario", "Usuario")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.ConfiguracionServicioTurno", b =>
                {
                    b.HasOne("ProyectoCronoVianda.Core.Models.Servicio", "Servicio")
                        .WithMany("ConfiguracionesTurno")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoCronoVianda.Core.Models.Turno", "Turno")
                        .WithMany("ConfiguracionesServicio")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Cronograma", b =>
                {
                    b.HasOne("ProyectoCronoVianda.Core.Models.Servicio", "Servicio")
                        .WithMany("Cronogramas")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.CronogramaItem", b =>
                {
                    b.HasOne("ProyectoCronoVianda.Core.Models.Cronograma", "Cronograma")
                        .WithMany("Items")
                        .HasForeignKey("IdCronograma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoCronoVianda.Core.Models.Empleado", "Empleado")
                        .WithMany("CronogramaItems")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoCronoVianda.Core.Models.Turno", "Turno")
                        .WithMany("CronogramaItems")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cronograma");

                    b.Navigation("Empleado");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Empleado", b =>
                {
                    b.HasOne("ProyectoCronoVianda.Core.Models.Servicio", "Servicio")
                        .WithMany("Empleados")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoCronoVianda.Core.Models.TipoDieta", "TipoDieta")
                        .WithMany("Empleados")
                        .HasForeignKey("TipoDietaId");

                    b.HasOne("ProyectoCronoVianda.Core.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Servicio");

                    b.Navigation("TipoDieta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Inasistencia", b =>
                {
                    b.HasOne("ProyectoCronoVianda.Core.Models.Empleado", "Empleado")
                        .WithMany("Inasistencias")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Menu", b =>
                {
                    b.HasOne("ProyectoCronoVianda.Core.Models.TipoDieta", "TipoDieta")
                        .WithMany("Menus")
                        .HasForeignKey("IdTipoDieta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDieta");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.SolicitudCambioTurno", b =>
                {
                    b.HasOne("ProyectoCronoVianda.Core.Models.Empleado", "Empleado")
                        .WithMany("SolicitudesCambio")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.UsuarioRol", b =>
                {
                    b.HasOne("ProyectoCronoVianda.Core.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoCronoVianda.Core.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.VentanaCambio", b =>
                {
                    b.HasOne("ProyectoCronoVianda.Core.Models.Servicio", "Servicio")
                        .WithMany("VentanasCambio")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoCronoVianda.Core.Models.TipoVianda", "TipoVianda")
                        .WithMany("VentanasCambio")
                        .HasForeignKey("IdTipoVianda")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoCronoVianda.Core.Models.Turno", "Turno")
                        .WithMany("VentanasCambio")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Servicio");

                    b.Navigation("TipoVianda");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Cronograma", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.CronogramaItem", b =>
                {
                    b.Navigation("AsignacionesVianda");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Empleado", b =>
                {
                    b.Navigation("CronogramaItems");

                    b.Navigation("Inasistencias");

                    b.Navigation("SolicitudesCambio");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Menu", b =>
                {
                    b.Navigation("AsignacionesVianda");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Servicio", b =>
                {
                    b.Navigation("ConfiguracionesTurno");

                    b.Navigation("Cronogramas");

                    b.Navigation("Empleados");

                    b.Navigation("VentanasCambio");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.TipoDieta", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Menus");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.TipoVianda", b =>
                {
                    b.Navigation("AsignacionesVianda");

                    b.Navigation("VentanasCambio");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Turno", b =>
                {
                    b.Navigation("ConfiguracionesServicio");

                    b.Navigation("CronogramaItems");

                    b.Navigation("VentanasCambio");
                });

            modelBuilder.Entity("ProyectoCronoVianda.Core.Models.Usuario", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
